# Generated by Django 4.0.1 on 2022-01-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_user_alter_tarea_comments_alter_tarea_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
