# Generated by Django 4.0.1 on 2022-01-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
