# Generated by Django 4.0.1 on 2022-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tarea_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='comments',
            field=models.TextField(max_length=250, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Descripción'),
        ),
    ]
