# Generated by Django 4.0.1 on 2022-01-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_tarea_comments_alter_tarea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='comments',
            field=models.TextField(max_length=250, null=True, verbose_name='Comentarios'),
        ),
    ]
